# Jekyll 配置文件
title: "我的博客"
description: "基于Jekyll和GitHub Pages的个人博客"
author: "Tyler"
email: your-email@example.com
baseurl: "" # GitHub Pages 项目的子路径，通常为空
url: "https://w-tyler.github.io" # 你的GitHub Pages URL

# 构建设置
markdown: kramdown
highlighter: rouge
theme: minima
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

# 分页设置
paginate: 5
paginate_path: "/page:num/"

# 排除文件
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

# 时区和语言
timezone: Asia/Shanghai
lang: zh-CN

# 社交链接（可选）
github_username: w-tyler
# twitter_username: your_twitter
# linkedin_username: your_linkedin

# 评论系统（可选）
# disqus:
#   shortname: your-disqus-shortname

# Google Analytics（可选）
# google_analytics: UA-XXXXXXXX-X

# 默认设置
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      comments: true 